server.port=${PORT:8080}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=${ADMIN_USER:kunal}
spring.security.user.password=${ADMIN_PASSWORD}

logging.level.org.springframework.web=DEBUG


app.jwt-secret-key=${JWT_SECRET_KEY}
app.jwt-expiration-ms=86400000
spring.datasource.hikari.connection-timeout=30000

